### ISSUE TITLE
Should `Responder` consume `self` to avoid the `AlreadyReplied` error case?

### ISSUE THREAD

**Issue by thomaseizinger** [oguzbilgener/bmrng#1]
I just started using the library and even though I overall really like it, this specific design decision surprised me a bit!

It seems too opinionated to force this signature onto the caller. More specifically, the current behaviour of the library can always be built on top of a "consuming" signature. One simply has to wrap the responder in an `Option` if desired.

However, from my usage experience so far, `Responder` is usually a local variable and hence fine to be consumed by the `respond` method.

What do you think?

**Comment by oguzbilgener** [comment]
Hi there, thank you for checking out my library and opening this issue.

Now that I look at this again, I agree with you. `Responder` is a local variable in my experience as well. 

I had a bit of free time tonight, and I went ahead and opened a PR: #2 

Please check it out. :slightly_smiling_face:

**Comment by thomaseizinger** [comment]
Fixed in #2. Thank you!
