### ISSUE TITLE
`ReceiveError` does not implement `std::error::Error`

### ISSUE THREAD

**Issue by thomaseizinger** [oguzbilgener/bmrng#3]
This can be worked around by converting it into a `RequestError` or using `send_receive` but I think the cleaner solution would be to simply implement `std::error::Error` for this type as well :)

**Comment by oguzbilgener** [comment]
Nice catch! thank you. I released v0.5.1 with a fix for this as it's a small change but feel free to leave comments. ✌️

**Comment by thomaseizinger** [comment]
Thank you! This can be closed then!
